# Podfile content
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'spotinapp' do
  pod 'AppCenter/Push', '~> 1.10.0'
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', path: '../node_modules/react-native', :subspecs => [
        'Core',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'DevSupport'
    ]

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
    pod 'react-native-maps', path: '../node_modules/react-native-maps/'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'  # <~~ if you need GoogleMaps support on iOS
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'

  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "react-native-google-maps"
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
          target.remove_from_project
        end
        targets_to_ignore = %w(React yoga)
        
        if targets_to_ignore.include? target.name
            target.remove_from_project
        end
    end
end
